# Generated by Django 4.2 on 2025-04-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cloud_app", "0004_sharablelink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
